app/main/routes.py
from flask import Blueprint, request, render_template, redirect, url_for, flash, jsonify
from flask_login import login_user, logout_user, login_required, current_user
from .forms import CafeForm, LoginForm, RegistrationForm
from .models import db, Cafe, User
from werkzeug.utils import secure_filename
from functools import wraps
from config import Config
from datetime import datetime, timedelta
from fuzzywuzzy import fuzz
from uuid import uuid4
import jwt
import os


UPLOAD_FOLDER = 'app/main/static/assets/img_uploads'
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg'}

main = Blueprint('main', __name__)


def admin_required(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        if not current_user.is_authenticated:
            return jsonify({'message': 'Authentication required! Please log in.'}), 401

        if not current_user.is_admin:
            return jsonify({'message': 'Access denied! Admin privileges required.'}), 403

        return func(*args, **kwargs)

    return wrapper


def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


def generate_token(user_id):
    """Generates a JWT token with an expiration time of 1 hour."""
    expiration = datetime.utcnow() + timedelta(hours=1)
    token = jwt.encode({
        'user_id': user_id,
        'exp': expiration
    }, Config.API_KEY, algorithm="HS256")
    return token


@main.route('/')
def home():
    """Displays the homepage."""
    return render_template('index.html', user=current_user)


@main.route('/register', methods=['GET', 'POST'])
def register():
    """Registers a new user."""
    user_logged_in = False

    if current_user.is_authenticated:
        flash('User already logged in! Please log out first.', 'info')
        user_logged_in = True

    form = RegistrationForm()

    if form.validate_on_submit() and not user_logged_in:
        form.email.data = form.email.data.lower()
        username = form.create_username(form.email.data)
        new_user = User(username=username, email=form.email.data)
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash('Registration successful! Please sign in.', 'success')
        return redirect(url_for('main.login'))

    # Flash errors
    if form.errors:
        for field, errors in form.errors.items():
            for error in errors:
                flash(f"{getattr(form, field).label.text} - {error}", 'error')

    return render_template('register.html', form=form, user_logged_in=user_logged_in)


@main.route('/login', methods=['GET', 'POST'])
def login():
    """Logs in a user."""
    next_page = request.args.get('next')

    if current_user.is_authenticated:
        flash('You are already logged in!', 'info')
        return redirect(url_for('main.home'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash('Login successful!', 'success')
            flash(f'Welcome {user.username}!', 'success')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Invalid email or password. Please try again.', 'error')

    if form.errors:
        for field, errors in form.errors.items():
            for error in errors:
                flash(f"{getattr(form, field).label.text} - {error}", 'error')

    return render_template('login.html', form=form)


@main.route('/logout')
@login_required
def logout():
    """Logs out a user."""
    next_page = request.args.get('next_page')
    print(next_page)
    logout_user()
    flash('You have been logged out.', 'success')
    return redirect(url_for(next_page)) if next_page else redirect(url_for('main.home'))


@main.route('/add', methods=['GET', 'POST'])
@login_required
def add_cafe():
    """Adds a new cafe to the database."""
    form = CafeForm()

    if form.validate_on_submit():
        image_files = request.files.getlist('images')
        filepaths = []
        for image_file in image_files:
            if image_file and allowed_file(image_file.filename):
                filename = secure_filename(image_file.filename)
                unique_filename = f"{uuid4().hex}_{filename}"
                filepath = os.path.join(UPLOAD_FOLDER, unique_filename)
                image_file.save(filepath)
                filepaths.append(filepath)

        new_cafe = Cafe(
            name=form.name.data,
            map_url=form.map_url.data,
            city=form.city.data,
            country=form.country.data,
            coffee_price=form.coffee_price.data,
            currency=form.currency.data,
            wifi_strength=int(form.wifi_strength.data),
            seats=form.seats.data,
            has_sockets=(form.has_sockets.data == 'True'),
            has_toilet=(form.has_toilet.data == 'True'),
            images=",".join(filepaths),
            full_review=form.full_review.data,
            full_rating=form.full_rating.data
        )
        db.session.add(new_cafe)
        db.session.commit()
        return redirect(url_for('main.give_feedback', action='add'))

    # Flash errors
    if form.errors:
        for field, errors in form.errors.items():
            for error in errors:
                flash(f"{getattr(form, field).label.text} - {error}", 'error')

    return render_template('add.html', form=form)


@main.route('/update/<int:cafe_id>', methods=['GET', 'PATCH', 'POST'])
@login_required
@admin_required
def update_cafe(cafe_id):
    """Updates the details of a specific cafe."""
    cafe = Cafe.query.get(cafe_id)
    if not cafe:
        flash('Cafe not found!', 'error')
        return redirect(url_for('main.give_feedback', action='notfound'))

    form = CafeForm(obj=cafe)

    if request.method == 'GET':
        # Render template with prepopulated data
        return render_template('update.html', form=form, cafe=cafe)

    elif request.method in ['POST', 'PATCH']:
        if form.validate_on_submit():
            form.populate_obj(cafe)
            # Manually convert string boolean fields to actual booleans
            cafe.has_sockets = form.has_sockets.data == 'True'
            cafe.has_toilet = form.has_toilet.data == 'True'
            # Handle file uploads
            image_files = request.files.getlist('images')
            if image_files and image_files[0].filename != '':
                filepaths = []
                for image_file in image_files:
                    if image_file and allowed_file(image_file.filename):
                        filename = secure_filename(image_file.filename)
                        unique_filename = f"{uuid4().hex}_{filename}"
                        filepath = os.path.join(UPLOAD_FOLDER, unique_filename)
                        image_file.save(filepath)
                        filepaths.append(filepath)
                cafe.images = ",".join(filepaths)

            db.session.commit()
            return redirect(url_for('main.give_feedback', action='update'))

        if form.errors:
            for field, errors in form.errors.items():
                for error in errors:
                    flash(f"{getattr(form, field).label.text} - {error}", 'error')

    return render_template('update.html', form=form, cafe=cafe)


@main.route('/feedback', methods=['GET'])
@login_required
def give_feedback():
    """Gives feedback after adding or updating a cafe."""
    action = request.args.get('action')
    return render_template('feedback.html', action=action)


@main.route('/all', methods=['GET', 'POST'])
def get_all_cafes():
    """Retrieves all cafes from the database."""
    is_rated = request.args.get('is_rated')
    all_cafes = Cafe.query.all()
    cafes_list = [cafe.to_dict() for cafe in all_cafes]
    for cafe in cafes_list:
        cafe['country'] = cafe['country'].split('(')[1].strip(')')

    if is_rated:
        cafes_list = [cafe for cafe in cafes_list if cafe['full_rating'] == 5]
        cafes_list = sorted(cafes_list, key=lambda cafe: cafe['full_rating'], reverse=True)

    cafe_columns = ["Name", "Map URL", "Location", "Coffee Price", "Wifi Strength", "Seats", "Has Sockets",
                    "Has Toilet", "Cafe Rating"]
    return render_template('cafes.html', cafe_rows=cafes_list, cafe_columns=cafe_columns, is_rated=is_rated)


@main.route('/search', methods=['GET'])
def search_cafes():
    """Searches for cafes based on user input."""
    find_nearby = request.args.get('nearby')
    form = CafeForm()

    query = request.args.get('query') or request.args.get('city')
    cafes_list = Cafe.query.all()
    matching_cafes = []

    if query:
        for cafe in cafes_list:
            if (fuzz.partial_ratio(query.lower(), cafe.name.lower()) > 70 or
                    fuzz.partial_ratio(query.lower(), cafe.city.lower()) > 70 or
                    fuzz.partial_ratio(query.lower(), cafe.country.lower()) > 70):
                matching_cafes.append(cafe.to_dict())
        if not matching_cafes:
            flash("Sorry, no cafes matching your search criteria were found.", "info")
    else:
        if not find_nearby:
            flash("Please enter a search query.", "info")

    cafe_columns = ["Name", "Map URL", "Location", "Coffee Price", "Wifi Strength", "Seats", "Has Sockets",
                    "Has Toilet", "Cafe Rating"]

    return render_template('cafes.html', cafe_rows=matching_cafes, cafe_columns=cafe_columns,
                           find_nearby=find_nearby, form=form, mode="search")


@main.route('/delete_cafe/<int:cafe_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def delete_cafe(cafe_id):
    """Deletes a cafe from the database."""
    cafe = Cafe.query.get(cafe_id)
    if not cafe:
        return redirect(url_for('main.give_feedback', action='notfound'))

app/main/templates/feedback.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
    <meta content="Mark Otto, Jacob Thornton, and Bootstrap contributors" name="author">
    <meta content="Hugo 0.122.0" name="generator">
    <meta content="" name="description">
    <meta content="" name="keywords">
    <title>{% if action == "add" or action == "update" or action == "delete" %} Success {% else %} Not Found {% endif %}</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link crossorigin href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet">

    <!-- CSS -->
    <link href="../static/css/bootstrap/vendor_1/bootstrap.min.css" rel="stylesheet">
    <link href="../static/css/bootstrap/vendor_2/aos/aos.css" rel="stylesheet">
    <link href="https://unpkg.com/aos@2.3.4/dist/aos.css" rel="stylesheet">
    <link href="../static/css/custom/custom.css" rel="stylesheet">
    <link href="../static/css/custom/main.css" rel="stylesheet">

    <style>
        main {
            background-color: white;
            color: white;
            position: relative;
            z-index: 1;
            background: white;
            background-size: cover;
            background-repeat: no-repeat;
            background-position: center center;
            min-height: 100vh;
            overflow-x: hidden;
            display: flex;
            justify-content: center;
            align-items: center;
            margin-bottom: 50px;
        }

        main::before {
            content: "";
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            z-index: -1;
            background: linear-gradient(to left, #ffffff, #f1f1f1, #F2DDB2);
        }

        #header {
            background: linear-gradient(to left,  #333333, #85785D);
        }

        h2 {
            color: var(--bs-body-color) !important;
            text-align: center;
            font-weight: 600 !important;
            margin-top: 0 !important;
            margin-bottom: 1rem !important;
        }

        .footer {
            background: linear-gradient(to left, #21201E,  #333333, #85785D);
            height: 100%;
            padding: 5px;
            position: relative;
            z-index: 2;
        }

        .terms-link {
            color: #0d81fd;
        }

        .terms-link:hover {
            color: #0d6dd3;
        }
    </style>
</head>

<body>
    <!-- SVG Icons -->
    <svg class="d-none" xmlns="http://www.w3.org/2000/svg">
        <symbol id="twitter" viewBox="0 0 16 16">
            <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
        </symbol>
        <symbol id="instagram" viewBox="0 0 16 16">
            <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334"/>
        </symbol>
        <symbol id="discord" viewBox="0 0 16 16">
            <path d="M13.545 2.907a13.2 13.2 0 0 0-3.257-1.011.05.05 0 0 0-.052.025c-.141.25-.297.577-.406.833a12.2 12.2 0 0 0-3.658 0 8 8 0 0 0-.412-.833.05.05 0 0 0-.052-.025c-1.125.194-2.22.534-3.257 1.011a.04.04 0 0 0-.021.018C.356 6.024-.213 9.047.066 12.032q.003.022.021.037a13.3 13.3 0 0 0 3.995 2.02.05.05 0 0 0 .056-.019q.463-.63.818-1.329a.05.05 0 0 0-.01-.059l-.018-.011a9 9 0 0 1-1.248-.595.05.05 0 0 1-.02-.066l.015-.019q.127-.095.248-.195a.05.05 0 0 1 .051-.007c2.619 1.196 5.454 1.196 8.041 0a.05.05 0 0 1 .053.007q.121.1.248.195a.05.05 0 0 1-.004.085 8 8 0 0 1-1.249.594.05.05 0 0 0-.03.03.05.05 0 0 0 .003.041c.24.465.515.909.817 1.329a.05.05 0 0 0 .056.019 13.2 13.2 0 0 0 4.001-2.02.05.05 0 0 0 .021-.037c.334-3.466-.559-6.449-2.32-9.107a.034.034 0 0 0-.021-.018ZM5.78 10.837c-.789 0-1.448-.724-1.448-1.612 0-.889.64-1.613 1.448-1.613.812 0 1.462.73 1.448 1.613 0 .888-.64 1.612-1.448 1.612Zm4.447 0c-.788 0-1.448-.724-1.448-1.612 0-.889.64-1.613 1.448-1.613.812 0 1.462.73 1.448 1.613 0 .888-.636 1.612-1.448 1.612Z"/>
        </symbol>
        <symbol id="github" viewBox="0 0 16 16">
            <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8"/>
        </symbol>
    </svg>

    <!-- Navbar -->
    <header class="header d-flex align-items-center fixed-top" id="header">
        <div class="container-fluid container-xl position-relative d-flex align-items-center justify-content-between">
            <a class="logo d-flex align-items-center me-auto me-lg-0" href="{{ url_for('main.home') }}">
                <h1 class="sitename">CC</h1>
                <span class="square-period-logo"></span>
            </a>
            <nav class="navmenu" id="navmenu">
                <ul>
                    <li><a href="{{ url_for('main.home') }}">Home</a></li>
                    <li><a href="{{ url_for('main.register') }}">Register</a></li>
                    <li class="active"><a href="{{ url_for('main.add_cafe') }}">Add Cafe</a></li>
                    <li><a href="{{ url_for ('main.get_all_cafes') }}">Cafe Repository</a></li>
                </ul>
                <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
            </nav>
            <a class="btn-getstarted" href="{{ url_for('main.logout') }}">Logout</a>
        </div>
    </header>

    <main>
        <div class="container text-center">
            <h2 class="h2" style="font-family: var(--nav-font)">
                {% if action == 'add' %}
                	{{ 'Successfully added new cafe!' }}
                {% elif action == 'update' %}
                	{{ 'Cafe details updated successfully!' }}
                {% elif action == 'notfound' %}
                	{{ 'Sorry, cafe was not found.' }}
                {% elif action == 'delete' %}
                    {{ 'Cafe has been deleted successfully.' }}
                {% endif %}
            </h2>
            <div class="d-flex justify-content-center mt-4">
                <a class="btn btn-primary btn-lg get-started-btn" href="{{ url_for('main.get_all_cafes') }}">
					All Cafes
				</a>
            </div>
        </div>
    </main>

    <!-- Footer -->
    <footer class="footer text-white" data-bs-theme="dark">
        <div class="container text-center">
            <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top"
                 style="border-color: #4D5256 !important">
                <p>&copy; 2024 CafeConnect Inc. All rights reserved.</p>
                <p class="mb-0">
                    <a class="terms-footer" href="#">Terms of Service</a> |
                    <a class="terms-footer" href="#">Privacy Policy</a>
                </p>
                <div class="social-links d-flex">
                    <a class="twitter d-flex align-items-center justify-content-center" href="#">
                        <svg class="bi" height="24" width="24">
                            <use xlink:href="#twitter"></use>
                        </svg>
                    </a>
                    <a class="instagram d-flex align-items-center justify-content-center" href="#">
                        <svg class="bi" height="24" width="24">
                            <use xlink:href="#instagram"></use>
                        </svg>
                    </a>
                    <a class="discord d-flex align-items-center justify-content-center" href="#">
                        <svg class="bi" height="24" width="24">
                            <use xlink:href="#discord"></use>
                        </svg>
                    </a>
                    <a class="github d-flex align-items-center justify-content-center" href="#">
                        <svg class="bi" height="24" width="24">
                            <use xlink:href="#github"></use>
                        </svg>
                    </a>
                </div>
            </div>
        </div>
    </footer>

    <!-- JavaScript -->
    <script src="../static/css/bootstrap/vendor_2/aos/aos.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://unpkg.com/aos@2.3.4/dist/aos.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>